### ISSUE TITLE
希望增加一个去掉京东任务脚本的版本

### ISSUE THREAD

**Issue by cocacolafan** [deezertidal/shadowrocket-rules#12]
使用很好。就是不需要京东脚本，他一直在通知栏跳消息

**Comment by deezertidal** [comment]
> 使用很好。就是不需要京东脚本，他一直在通知栏跳消息

在shadowrocket中长按配置文件-编辑纯本文-删除或添加适合自己的规则或脚本 
做再多配置文件也不会适合所有人 建议根据个人偏好自定义自己的配置文件 
该issue长期开放 希望更多人看到
