### ISSUE TITLE
关于增加模块

### ISSUE THREAD

**Issue by GD2021** [deezertidal/shadowrocket-rules#14]
能否增加火狐影视
https://gitlab.com/ioshkj/quantumultx/-/raw/main/vipjs/huohuvip.conf

**Comment by deezertidal** [comment]
> 能否增加火狐影视
> https://gitlab.com/ioshkj/quantumultx/-/raw/main/vipjs/huohuvip.conf


#!name=x
#!desc=x
[Script]
火狐影视恢复永久会员=type=http-reponse,pattern=^http:\/\/huo\.hzzykj\.net\/\/app\/api\/MembershipInformation,requires-body=1,script-path=https://gitlab.com/ioshkj/quantumultx/-/raw/main/vipjs/huohuvip.js
[Mitm]
hostname= %APPEND% huo.hzzykj.net
