### ISSUE TITLE
APP开屏去广告

### ISSUE THREAD

**Issue by guren777** [deezertidal/shadowrocket-rules#15]
大佬，能否恢复此模块的，拼多多去广告规则？！

**Comment by deezertidal** [comment]
> 大佬，能否恢复此模块的，拼多多去广告规则？！

[URL Rewrite]
^https?:\/\/api\.(pinduoduo|yangkeduo)\.com\/api\/cappuccino\/splash - reject

**Comment by guren777** [comment]
> > 大佬，能否恢复此模块的，拼多多去广告规则？！
> 
> 
> 
> [URL Rewrite]
> 
> ^https?:\/\/api\.(pinduoduo|yangkeduo)\.com\/api\/cappuccino\/splash - reject

谢谢🙏大佬
