### ISSUE TITLE
使用shadowrocket_lite.conf，小火箭开启之后，抖音app无法访问网络

### ISSUE THREAD

**Issue by Hxd097** [deezertidal/shadowrocket-rules#16]
conf里面没有搜到抖音相关项目，可能是某个rule-set里面屏蔽了抖音？

**Comment by deezertidal** [comment]
> conf里面没有搜到抖音相关项目，可能是某个rule-set里面屏蔽了抖音？

应该是与某个重写冲突了 排查不出 shadowrocket-basic.conf无此问题
