### ISSUE TITLE
Spotify的模块失效了诶

### ISSUE THREAD

**Issue by baibai0222** [deezertidal/shadowrocket-rules#20]
Spotify的单独模块失效了，但是在配置文件里面的还能用。啥时候可以更新一下啊🥹🥹

**Comment by baibai0222** [comment]
> > Spotify的单独模块失效了，但是在配置文件里面的还能用。啥时候可以更新一下啊🥹🥹
> 
> 
> 
> 你大概有别的模块的hostname后面没有%APPEND%

**Comment by deezertidal** [comment]
> 每个模块都有哦，我还专门挨个检查过

那不知道了 只能你自己排查 选初始配置文件 模块全部取消勾选 单独勾选spotify  。配置文件里的spotify脚本跟Spotify模块是没区别的

**Comment by baibai0222** [comment]
> > 每个模块都有哦，我还专门挨个检查过
> 
> 
> 
> 那不知道了 只能你自己排查 选初始配置文件 模块全部取消勾选 单独勾选spotify  。配置文件里的spotify脚本跟Spotify模块是没区别的。
> 
> 还有一种可能是你的去广告相关的规则或模块脚本跟spotfiy模块冲突了

好的好的，谢谢🙏🏻
