### ISSUE TITLE
xmind模块

### ISSUE THREAD

**Issue by Leon666-554** [deezertidal/shadowrocket-rules#24]
xmind模块添加了以后，在AppStore下载后没有显示订阅到2030年

**Comment by deezertidal** [comment]
> xmind模块添加了以后，在AppStore下载后没有显示订阅到2030年

更新模块

**Comment by Leon666-554** [comment]
更新了还是不行😭

**Comment by deezertidal** [comment]
>

> 更新了还是不行😭

登录账号 小火箭重连 Xmind划掉后台再打开 稍等一分钟 我这边测试下来没问题

**Comment by Leon666-554** [comment]
重复好多次了还是不行

**Comment by Leon666-554** [comment]
是不是iOS14不可以啊 iOS15成功了

**Comment by deezertidal** [comment]
> 是不是iOS14不可以啊 iOS15成功了

应该跟ios版本无关 应该是你ios14上的小火箭存在冲突模块吧

**Comment by Leon666-554** [comment]
只装了这一个

> > 是不是iOS14不可以啊 iOS15成功了
> 
> 应该跟ios版本无关 应该是你ios14上的小火箭存在冲突模块吧

Duplicate of #只装了这一个😭
