### ISSUE TITLE
大佬，可以更新下Lightroom

### ISSUE THREAD

**Issue by Rany8864** [deezertidal/shadowrocket-rules#26]
这个是可用的JS，https://github.com/89996462/Quantumult-X/blob/main/ycdz/lightroom.js

**Comment by deezertidal** [comment]
> 这个是可用的JS，https://github.com/89996462/Quantumult-X/blob/main/ycdz/lightroom.js

两个脚本一样的 一个加密一个没加密。 loon端测试正常 小火箭我不常用 晚点看看

**Comment by Rany8864** [comment]
> > 这个是可用的JS，https://github.com/89996462/Quantumult-X/blob/main/ycdz/lightroom.js
> 
> 两个脚本一样的 一个加密一个没加密。 loon端测试正常 小火箭我不常用 晚点看看

谢谢大佬，小火箭端的VSCO好像也不能正常解锁

**Comment by deezertidal** [comment]
> > > 这个是可用的JS，https://github.com/89996462/Quantumult-X/blob/main/ycdz/lightroom.js
> > 
> > 
> > 两个脚本一样的 一个加密一个没加密。 loon端测试正常 小火箭我不常用 晚点看看
> 
> 谢谢大佬，小火箭端的VSCO好像也不能正常解锁

刚刚试了一下小火箭 两个都正常啊 。vsco显示活跃用户 ，Lightroom显示已订阅 功能也都能用
