### ISSUE TITLE
没有找到番茄小说去广告的模块

### ISSUE THREAD

**Issue by chengkongyiban** [deezertidal/shadowrocket-rules#3]
没有找到番茄小说去广告的模块

**Comment by deezertidal** [comment]
漏掉了 已添加。 将https://raw.githubusercontent.com/deezertidal/shadowrocket-rules/main/modules/fanqie.module添加到配置-模块。仅移植 自行测试有效性

**Comment by deezertidal** [comment]
https://raw.githubusercontent.com/deezertidal/shadowrocket-rules/main/modules/fanqie.module

**Comment by deezertidal** [comment]
> https://raw.githubusercontent.com/deezertidal/shadowrocket-rules/main/modules/fanqie.module



> 没有找到番茄小说去广告的模块

https://raw.githubusercontent.com/deezertidal/shadowrocket-rules/main/modules/fanqie.module
