### ISSUE TITLE
配置之后 小火箭全局路由选什么模式啊

### ISSUE THREAD

**Issue by 1275688416** [deezertidal/shadowrocket-rules#4]
我选择的是配置模式 但是一打应用就会断掉连接，选择代理模式配置文件的功能又都没有实现 。。。

**Comment by 1275688416** [comment]
配置文件是昨天晚上下载的 我刚才又尝试了一下 在确保证书已经信任的情况下 打开连接等一会儿就会断掉。。 甚至不需要切出去 我小火箭有两个梯子的订阅 都尝试了一下都没有成功 系统的话是ios15.6.1的 小火箭版本是2.1.90的 之前尝试过的软件有spotify 和酷我音乐吧 想着试一下破解会员的功能有没有实现

**Comment by deezertidal** [comment]
> 配置文件是昨天晚上下载的 我刚才又尝试了一下 在确保证书已经信任的情况下 打开连接等一会儿就会断掉。。 甚至不需要切出去 我小火箭有两个梯子的订阅 都尝试了一下都没有成功 系统的话是ios15.6.1的 小火箭版本是2.1.90的 之前尝试过的软件有spotify 和酷我音乐吧 想着试一下破解会员的功能有没有实现

https://raw.githubusercontent.com/deezertidal/shadowrocket-rules/main/shadowrocket_lite.conf
试试这个简单规则的配置

**Comment by 1275688416** [comment]
这个规则不会断开连接 这个规则有什么功能呢

**Comment by deezertidal** [comment]
> 这个规则不会断开连接 这个规则有什么功能呢

简单规则就是墙外的都走代理节点 墙内的都直连。 可以满足95%的需求。复杂点的代理分组 可以指定某个应用走某个国家的节点

**Comment by 1275688416** [comment]
好的谢谢 第一次接触这个东西 不太了解
